from typing import Any
from ..config import PressureConfig

class PressureSensor:
    def __init__(self, serial_instance: Any = ..., period_s: float | None = ...,
                 response_timeout_s: float | None = ...,
                 queue_size: int | None = ..., readiness_waiter: Any = ...,
                 port: str | None = ..., baudrate: int | None = ...,
                 _use_process: bool | None = ..., _mp_context: Any = ...,
                 _process_factory: Any = ...,
                 _startup_timeout_s: float | None = ...,
                 _frame_sink: Any = ..., _status_sink: Any = ...,
                 config: PressureConfig | None = ...) -> None: ...
    @staticmethod
    def crc8_itu(data: bytes) -> int: ...
    def open_port(self) -> None: ...
    def read_data(self) -> bytes | None: ...
    def read_frame(self, timeout_s: float = ...) -> dict[str, Any] | None: ...
    def get_timing_stats(self) -> dict[str, Any]: ...
    def decode(self, payload: bytes) -> list[int]: ...
    def close(self) -> None: ...
