from typing import Any

class TimestampedBuffer:
    def __init__(self, maxlen: int = ...) -> None: ...
    def append(self, item: dict[str, Any]) -> int: ...
    def get_latest(self) -> dict[str, Any] | None: ...
    def get_after(self, seq: int) -> list[dict[str, Any]]: ...
    def find_closest(self, ts: float, max_diff_s: float | None = ...,
                     min_seq: int = ...) -> dict[str, Any] | None: ...

def match_closest(buf: TimestampedBuffer, ts: float, max_diff_s: float,
                  min_seq: int = ...) -> dict[str, Any] | None: ...
