from typing import Any
from ..config import ForceConfig

class SixAxisForceSensor:
    def __init__(self, serial_instance: Any = ..., period_s: float | None = ...,
                 response_timeout_s: float | None = ...,
                 queue_size: int | None = ..., readiness_waiter: Any = ...,
                 port: str | None = ..., baudrate: int | None = ...,
                 _use_process: bool | None = ..., _mp_context: Any = ...,
                 _process_factory: Any = ...,
                 _startup_timeout_s: float | None = ...,
                 _status_sink: Any = ...,
                 config: ForceConfig | None = ...) -> None: ...
    def open_port(self) -> None: ...
    def read_frame(self, timeout_s: float = ...) -> dict[str, Any] | None: ...
    def read(self) -> list[float] | None: ...
    def calibrate_zero(self, sample_count: int = ...,
                       timeout_s: float = ...) -> bool: ...
    def add_zero_bias(self, fx: float, fy: float) -> None: ...
    def get_timing_stats(self) -> dict[str, Any]: ...
    def close(self) -> None: ...
