from .config import FullApplicationConfig

def run_application(config: FullApplicationConfig | None = ...) -> int: ...
def run_dual_application(config_a: FullApplicationConfig,
                         config_b: FullApplicationConfig) -> int: ...
