from typing import Any
from ..config import FullApplicationConfig

class PressureThread:
    error: BaseException | None
    def __init__(self, sensor: Any, buffer: Any, stop_event: Any) -> None: ...
    def start(self) -> None: ...
    def join(self, timeout: float | None = ...) -> None: ...

class ForceThread(PressureThread): ...

class FullAcquisitionSession:
    def __init__(self, plot: Any, config: FullApplicationConfig | None = ...,
                 stop_event: Any = ..., pressure_factory: Any = ...,
                 force_factory: Any = ..., sample_processor: Any = ...,
                 spectrum_sink: Any = ..., enable_spectrum: bool = ...) -> None: ...
    def start(self) -> FullAcquisitionSession: ...
    def should_stop(self) -> bool: ...
    def check_errors(self) -> None: ...
    def schedule_rezero(self, reason: str) -> None: ...
    def process_new_pressure_frames(self) -> int: ...
    def write_snapshot(self, sample: Any, force_item: Any) -> None: ...
    def drain_force_matches(self, now: float | None = ...) -> None: ...
    def log_timing_stats(self, now: float | None = ...) -> None: ...
    def update_plot(self) -> None: ...
    def wait_for_next_iteration(self) -> None: ...
    def close(self) -> None: ...

class FullApplicationRunner:
    def __init__(self, worker_target: Any,
                 config: FullApplicationConfig | None = ...,
                 plot_factory: Any = ...) -> None: ...
    def run(self) -> None: ...

class DualApplicationRunner:
    def __init__(self, config_a: FullApplicationConfig,
                 config_b: FullApplicationConfig,
                 worker_target: Any = ..., plot_factory: Any = ...) -> None: ...
    def run(self) -> None: ...

def acquisition_loop(plot: Any, stop_event: Any = ...,
                     config: FullApplicationConfig | None = ...,
                     session_factory: Any = ..., spectrum_sink: Any = ...,
                     enable_spectrum: bool = ..., **kwargs: Any) -> None: ...
