from typing import Any
import numpy as np
from ..config import CopConfig

class PRSensorAngle:
    def __init__(self, rows: int | None = ..., cols: int | None = ...,
                 total_threshold_factor: float | None = ...,
                 pixel_threshold_factor: float | None = ...,
                 collect_frames: int | None = ...,
                 stability_frames: int | None = ...,
                 reset_at_frame: int | None = ..., refine_cnt: int | None = ...,
                 refine_distance: float | None = ..., merge_ratio: float | None = ...,
                 region_match_dist: float | None = ...,
                 region_min_area: int | None = ...,
                 region_peak_ratio: float | None = ...,
                 region_peak_dist: int | None = ...,
                 config: CopConfig | None = ...) -> None: ...
    def get_all(self, adc_data: Any) -> tuple[float, float, float, float, float]: ...
    def get_cop(self, adc_data: Any) -> tuple[float, float]: ...
    def get_gradient(self, adc_data: Any) -> np.ndarray: ...
    def get_origin(self) -> tuple[float | None, float | None]: ...
    def get_state(self) -> int: ...
    def is_motion_ready(self) -> bool: ...
    def reset_origin(self) -> None: ...
    def reanchor_origin(self, cop_x: float, cop_y: float) -> None: ...
    def get_region_state(self, region_id: int) -> dict[str, Any]: ...
    def dynamic_threshold(self, frame2d: np.ndarray) -> None: ...
